### ISSUE TITLE
I got error

### ISSUE THREAD

**Issue by MHendriF** [bactiar291/auto-tx-unichain#2]
![Screenshot 2024-10-26 155119](https://github.com/user-attachments/assets/6d3de354-5be7-418b-9176-866a134d3970)

**Comment by bactiar291** [comment]
ambil addresnya dari bitget atau trust wallet di receive biar besar
kecilnya hurup kebaca sama ens eth ,private key tetep sama done moga
membantu

Pada Sab, 26 Okt 2024 19.28, M Hendri Febriansyah ***@***.***>
menulis:

**Comment by MHendriF** [comment]
Done, ternyata ada beberapa huruf yg besar kecilnya beda. Sebelumnya saya export dari wallet MetaMask. 
Thanks

**Comment by bactiar291** [comment]
Siap

Pada Sab, 26 Okt 2024 21.03, M Hendri Febriansyah ***@***.***>
menulis:
